<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="Components\_Imports.razor">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
        <PackageReference Include="Microsoft.Extensions.Localization" />
        <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
        <PackageReference Include="Microsoft.Kiota.Abstractions" />
        <PackageReference Include="Radzen.Blazor" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Localizations\Translations.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Translations.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Localizations\Translations.nl.resx">
        <DependentUpon>Translations.resx</DependentUpon>
      </EmbeddedResource>
      <Compile Update="Localizations\Translations.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Translations.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
